// src/data.js
export const products = [
  {
    product_id: 1,
    product_title: "Dell XPS 13",
    product_image: "/path/to/image1.jpg",
    category: "Laptops",
    price: 999.99,
    description: "High-performance laptop with powerful features.",
    Specification: ["Intel i7", "16GB RAM", "512GB SSD"],
    availability: true,
    rating: 4.5,
  },
  {
    product_id: 2,
    product_title: "MacBook Air M1",
    product_image: "/path/to/image2.jpg",
    category: "MacBook",
    price: 1299.99,
    description: "Apple’s lightweight and powerful MacBook with M1 chip.",
    Specification: ["Apple M1", "8GB RAM", "256GB SSD"],
    availability: true,
    rating: 4.8,
  },
  {
    product_id: 3,
    product_title: "HP Spectre x360",
    product_image: "/path/to/image3.jpg",
    category: "Laptops",
    price: 1150.00,
    description: "Versatile laptop with a 360-degree hinge and touch screen.",
    Specification: ["Intel i7", "16GB RAM", "512GB SSD"],
    availability: false,
    rating: 4.3,
  },
  {
    product_id: 7,
    product_title: "iPhone 13 Pro",
    product_image: "/path/to/image7.jpg",
    category: "Phones",
    price: 999.99,
    description: "Apple’s latest smartphone with advanced camera features.",
    Specification: ["A15 Bionic Chip", "128GB Storage", "5G Support"],
    availability: true,
    rating: 4.9,
  },
  {
    product_id: 13,
    product_title: "Anker PowerCore 20000",
    product_image: "/path/to/image13.jpg",
    category: "Accessories",
    price: 59.99,
    description: "Portable power bank with fast charging capabilities.",
    Specification: ["20000mAh", "USB-C", "PowerIQ Technology"],
    availability: true,
    rating: 4.8,
  },
  {
    product_id: 14,
    product_title: "Logitech MX Master 3",
    product_image: "/path/to/image14.jpg",
    category: "Accessories",
    price: 99.99,
    description: "Advanced ergonomic wireless mouse for productivity.",
    Specification: ["Ergonomic Design", "USB-C Charging", "7 Buttons"],
    availability: true,
    rating: 4.9,
  },
  {
    product_id: 19,
    product_title: "Apple Watch Series 7",
    product_image: "/path/to/image19.jpg",
    category: "Smart Watches",
    price: 399.00,
    description: "Advanced smartwatch with health tracking features.",
    Specification: ["Always-On Display", "Blood Oxygen Monitoring", "GPS"],
    availability: true,
    rating: 4.7,
  },
  {
    product_id: 22,
    product_title: "MacBook Air 13-inch M2",
    product_image: "/path/to/image22.jpg",
    category: "MacBook",
    price: 1299.99,
    description: "Lightweight MacBook Air with M2 chip for everyday use.",
    Specification: ["Apple M2", "8GB RAM", "256GB SSD"],
    availability: true,
    rating: 4.8,
  },
  {
    product_id: 23,
    product_title: "iPhone 14 Pro Max",
    product_image: "/path/to/image23.jpg",
    category: "iPhone",
    price: 1099.99,
    description: "Apple’s latest flagship iPhone with improved cameras and performance.",
    Specification: ["A16 Bionic Chip", "128GB Storage", "5G Support"],
    availability: true,
    rating: 4.9,
  },
  {
    product_id: 24,
    product_title: "iPhone SE 2022",
    product_image: "/path/to/image24.jpg",
    category: "iPhone",
    price: 429.99,
    description: "Affordable iPhone with powerful A15 Bionic chip.",
    Specification: ["A15 Bionic Chip", "64GB Storage", "4G Support"],
    availability: true,
    rating: 4.6,
  }
];
